language: android

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository

jdk:
  - oraclejdk8

#sonatype username and password
env:
  global:
    - secure: "kKtE5tdRk0mHuEQfBo+nbl32l/coGJokFRNA8CsETlfasAwoAqAZjEuME61t1o8NIhkXieDs+dcYIl28GPxbcgdpF+Ja+ztMAZpgs3bEeGrQBx1appKHaUe2rOcJY79fHuNxeDrwMyl7b2Jcx1c9TBXG2SI95zsSQiHsWJixEqiJ5V8y/T0SmlSxwDc14Alt4cdFT+CtgkdJSZmKdubb65E8Z0s62N3TUcrAOR1e6tMccpEdXdMqZ19bnSp1m5FRx5dUuW0NmhIwSK6e32yy5Ei6MCtvIfBK+X3nSZx3sJ/wuZ36IDw6DJ6oGRj2eTJecswd9Oxlz22LERyl29nyzqQ73ch6h4f9pHW6LnJ0PICb1vn2FrR8SYNK6reoU/DnhI/Aixqqesu1k0TnxGcnmHnPTDOeOlkE2gwDb+2PbKK71b5GVBGb/SxXeu5Y5s1hO2y+3Z0OOVaDwrUgHFgZyUQxE1QiFhhBRBpjr5cxcNIvUc4yMBrPHZkTbNObMfLQgkkn8z89gFOMgkrWzMZSFEWN+8YhZjHVhe6PMBNOdBC2e7GojJdtCKcr5QSKeKf1laR2kTQpHpNmwAH6D/7+kpYpyMVKMER1h+sVHphr/lLB+/e/okCxti1Ngbjb7ml66Du4tzUzJILCaWELdvWCYDZpiZOTJnmoNswQYi/dUXU="
    - secure: "R5gXruIwczVo4yrBUKAagJ17YYQOgO+/2s+O2Qlbzn9GBavLK7mUXXHWNPSvEAFd66hTgdU8FXWVhmihUszE/ZFz19Bj/2eJAtT8XfDcfZ0qvU4V/6wgYzaFi11Rpa5e2gG/Wmkil6etn6PhB3nL0BQOEflOU7gnoRmhRHHQPBrIJG82vS46GBj3rVBJDQ51i5fK2qOl2B2h/KjwBy7aFLgzgcH65/Hc9TCXPnE8arFpUVxAg39BnsY1qMO+KZPgOBaoLOnlnKzc5vqNaX3FlsXR0jdcuU06zwkaO9+xodFpgzcED98Fc8cUMa8MvoW+FWo1gutapwb99IEk00f6+31OKl65gYkEt4pzD7LGN4Erove3ggJ3Pw5GQhOB99T/wPF6MWkwy57QIFDNQp8XV6r0ClzqCC57kz2iDtHK1u3tdBiuatg6/rX5JKhkJgBFwg0F5Ue2uur6J3sD3LVbX4xblEJ2Oc+xxer3vBSXhAs3vTrl6Sl5FwllEhp8ZrnD07nCMyrHiOC8wXEmNV7PDEnEcwGMq/Av3fDiTDWmj/h4rNMZj08jZR40Qjd9BP6Mycs/BtLyVMrjz1ZwjIgNB9/x1i3+QUVipEdA4e+O0pJNFJ5hm4P1JsclcNbMO1zqAvyF6vQWmOq6fnrG5bDxX2eK0TnDJtapwGooDijG6T8="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .buildscript/deploy_snapshot.sh
